import { League_Spartan } from "next/font/google";
import "./globals.css";

const leagueSpatan = League_Spartan({ subsets: ["latin"], display: 'swap', adjustFontFallback: false });

export const metadata = {
  title: "Fatima Code",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={leagueSpatan.className}>
          {children}
      </body>
    </html>
  );
}
